version: '3'

services:
  nodeapi:
    image: postgres
    container_name: database_nodeapi
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: nodeapi
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/usr/app
    links:
      - nodeapi
    depends_on:
      - nodeapi

volumes:
  pgdata:
    driver: local
